version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    env_file:
      - ./.production.env
    environment:
      - PATH=/root/.bun/bin:$PATH
    ports:
      - "5000:5000"
    command: sh -c "bun migrate && bun seed-all && bun run start"

volumes:
  db_data:
